USE [shopper_dev_app]
GO

SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

IF EXISTS (
            SELECT 1
            FROM sys.procedures with (nolock)
            WHERE NAME = 'wrkVendor'
                AND type = 'P'
           )
    DROP PROCEDURE [dbo].[wrkVendor]
GO

CREATE PROCEDURE [dbo].[wrkVendor] 

	
AS 

/*******************************************************************************************************
*   shopper_dev_app.dbo.wrkXddFile_Wrk
*
*   Creator: Michelle Morales    
*   Date: 03/08/2016          
*   
*          
*   Notes: 

*
*
*   Usage:	set statistics io on

	execute shopper_dev_app.dbo.wrkXddFile_Wrk 


*   Modifications:   
*   Developer Name      Date        Brief description
*   ------------------- ----------- ------------------------------------------------------------
*   
********************************************************************************************************/
---------------------------------------------
-- declare variables
---------------------------------------------

---------------------------------------------
-- create temp tables
---------------------------------------------

if object_id('tempdb.dbo.##HoursDataStage') > 0 drop table ##HoursDataStage

---------------------------------------------
-- set session variables
---------------------------------------------
SET NOCOUNT ON
--set xact_abort on    --only uncomment if you're usiSng a transaction, otherwise delete this line.

---------------------------------------------
-- body of stored procedure
---------------------------------------------
update s
	set AdjCrtd_DateTime = d.AdjCrtd_DateTime,
		AdjCrtd_Prog = d.AdjCrtd_Prog,
		AdjCrtd_User = d.AdjCrtd_User,
		AdjS4Future01 = d.AdjS4Future01,
		AdjS4Future02 = d.AdjS4Future02,
		AdjS4Future03 = d.AdjS4Future03,
		AdjS4Future04 = d.AdjS4Future04,
		AdjS4Future05 = d.AdjS4Future05,
		AdjS4Future06 = d.AdjS4Future06,
		AdjS4Future07 = d.AdjS4Future07,
		AdjS4Future08 = d.AdjS4Future08,
		AdjS4Future09 = d.AdjS4Future09,
		AdjS4Future10 = d.AdjS4Future10,
		AdjS4Future11 = d.AdjS4Future11,
		AdjS4Future12 = d.AdjS4Future12,
		BnkAcctType = d.BnkAcctType,
		BnkBankAcct = d.BnkBankAcct,
		BnkBankTransit = d.BnkBankTransit,
		BnkOrigDFI = d.BnkOrigDFI,
		BnkPNDate = d.BnkPNDate,
		BnkPNStatus = d.BnkPNStatus,
		BnkUser1 = d.BnkUser1,
		BnkUser10 = d.BnkUser10,
		BnkUser2 = d.BnkUser2,
		BnkUser3 = d.BnkUser3,
		BnkUser4 = d.BnkUser4,
		BnkUser5 = d.BnkUser5,
		BnkUser6 = d.BnkUser6,
		BnkUser7 = d.BnkUser7,
		BnkUser8 = d.BnkUser8,
		BnkUser9 = d.BnkUser9,
		ChkAcct = d.ChkAcct,
		ChkBatEFTGrp = d.ChkBatEFTGrp,
		ChkBatNbr = d.ChkBatNbr,
		ChkBatSeq = d.ChkBatSeq,
		ChkCpnyID = d.ChkCpnyID,
		ChkCuryAmt = d.ChkCuryAmt,
		ChkCuryDiscAmt = d.ChkCuryDiscAmt,
		ChkCuryID = d.ChkCuryID,
		ChkCuryRGOLAmt = d.ChkCuryRGOLAmt,
		ChkDocDate = d.ChkDocDate,
		ChkDocType = d.ChkDocType,
		ChkLUpd_DateTime = d.ChkLUpd_DateTime,
		ChkLUpd_Prog = d.ChkLUpd_Prog,
		ChkLUpd_User = d.ChkLUpd_User,
		ChkPerPost = d.ChkPerPost,
		ChkRefNbr = d.ChkRefNbr,
		ChkSub = d.ChkSub,
		ChkTerms = d.ChkTerms,
		ComputerName = d.ComputerName,
		Crtd_DateTime = d.Crtd_DateTime,
		Crtd_Prog = d.Crtd_Prog,
		Crtd_User = d.Crtd_User,
		DepAcctType = d.DepAcctType,
		DepBankAcct = d.DepBankAcct,
		DepBankAcctLen = d.DepBankAcctLen,
		DepBankTransit = d.DepBankTransit,
		DepBankTransitLen = d.DepBankTransitLen,
		DepEDIVersion = d.DepEDIVersion,
		DepEntryClass = d.DepEntryClass,
		DepISOCntry = d.DepISOCntry,
		DepPNDate = d.DepPNDate,
		DepPNStatus = d.DepPNStatus,
		DepPNTaxPmt = d.DepPNTaxPmt,
		DepRecord = d.DepRecord,
		DepUser1 = d.DepUser1,
		DepUser10 = d.DepUser10,
		DepUser2 = d.DepUser2,
		DepUser3 = d.DepUser3,
		DepUser4 = d.DepUser4,
		DepUser5 = d.DepUser5,
		DepUser6 = d.DepUser6,
		DepUser7 = d.DepUser7,
		DepUser8 = d.DepUser8,
		DepUser9 = d.DepUser9,
		EditScrnNbr = d.EditScrnNbr,
		FilACHCompanyID = d.FilACHCompanyID,
		FilACHCompanyIDLen = d.FilACHCompanyIDLen,
		FilACHCompanyName = d.FilACHCompanyName,
		FilACHCompanyNameLen = d.FilACHCompanyNameLen,
		FilACHImmDest = d.FilACHImmDest,
		FilACHImmDestLen = d.FilACHImmDestLen,
		FilACHImmDestN = d.FilACHImmDestN,
		FilACHImmDestNLen = d.FilACHImmDestNLen,
		FilACHImmOrig = d.FilACHImmOrig,
		FilACHImmOrigLen = d.FilACHImmOrigLen,
		FilACHImmOrigN = d.FilACHImmOrigN,
		FilACHImmOrigNLen = d.FilACHImmOrigNLen,
		FilCrLf = d.FilCrLf,
		FormatID = d.FormatID,
		KeepDelete = d.KeepDelete,
		LUpd_DateTime = d.LUpd_DateTime,
		LUpd_Prog = d.LUpd_Prog,
		LUpd_User = d.LUpd_User,
		PerAppl = d.PerAppl,
		RecordSumAmt = d.RecordSumAmt,
		RecordSummary = d.RecordSummary,
		RecSection = d.RecSection,
		RecType = d.RecType,
		SKFuture01 = d.SKFuture01,
		SKFuture02 = d.SKFuture02,
		SKFuture03 = d.SKFuture03,
		SKFuture04 = d.SKFuture04,
		SKFuture05 = d.SKFuture05,
		SKFuture06 = d.SKFuture06,
		SKFuture07 = d.SKFuture07,
		SKFuture08 = d.SKFuture08,
		SKFuture09 = d.SKFuture09,
		SKFuture10 = d.SKFuture10,
		SKFuture11 = d.SKFuture11,
		SKFuture12 = d.SKFuture12,
		User1 = d.User1,
		User10 = d.User10,
		User2 = d.User2,
		User3 = d.User3,
		User4 = d.User4,
		User5 = d.User5,
		User6 = d.User6,
		User7 = d.User7,
		User8 = d.User8,
		User9 = d.User9,
		ValueString = d.ValueString,
		VchAmt = d.VchAmt,
		VchAmtInChkCury = d.VchAmtInChkCury,
		VchCpnyID = d.VchCpnyID,
		VchCpnyIDEIN = d.VchCpnyIDEIN,
		VchCuryAmt = d.VchCuryAmt,
		VchCuryDiscAmt = d.VchCuryDiscAmt,
		VchCuryID = d.VchCuryID,
		VchCuryMultDiv = d.VchCuryMultDiv,
		VchCuryOrigDocAmt = d.VchCuryOrigDocAmt,
		VchCuryRate = d.VchCuryRate,
		VchDiscAmt = d.VchDiscAmt,
		VchDocDesc = d.VchDocDesc,
		VchDocType = d.VchDocType,
		VchInvcDate = d.VchInvcDate,
		VchInvcNbr = d.VchInvcNbr,
		VchPONbr = d.VchPONbr,
		VchRefNbr = d.VchRefNbr,
		VchUser1 = d.VchUser1,
		VchUser2 = d.VchUser2,
		VchUser3 = d.VchUser3,
		VchUser4 = d.VchUser4,
		VchUser5 = d.VchUser5,
		VchUser6 = d.VchUser6,
		VchUser7 = d.VchUser7,
		VchUser8 = d.VchUser8,
		VendCust = d.VendCust,
		VendID = d.VendID,
		VendName = d.VendName
from shopper_dev_app.dbo.XDDFile_Wrk s 
inner join den_dev_app.dbo.XDDFile_Wrk d
	on s.FileType = d.FileType
	and s.EBFileNbr = d.EBFileNbr
	and s.RecordID = d.RecordID


insert shopper_dev_app.dbo.xddFile_Wrk
(
	AdjCrtd_DateTime,
	AdjCrtd_Prog,
	AdjCrtd_User,
	AdjS4Future01,
	AdjS4Future02,
	AdjS4Future03,
	AdjS4Future04,
	AdjS4Future05,
	AdjS4Future06,
	AdjS4Future07,
	AdjS4Future08,
	AdjS4Future09,
	AdjS4Future10,
	AdjS4Future11,
	AdjS4Future12,
	BnkAcctType,
	BnkBankAcct,
	BnkBankTransit,
	BnkOrigDFI,
	BnkPNDate,
	BnkPNStatus,
	BnkUser1,
	BnkUser10,
	BnkUser2,
	BnkUser3,
	BnkUser4,
	BnkUser5,
	BnkUser6,
	BnkUser7,
	BnkUser8,
	BnkUser9,
	ChkAcct,
	ChkBatEFTGrp,
	ChkBatNbr,
	ChkBatSeq,
	ChkCpnyID,
	ChkCuryAmt,
	ChkCuryDiscAmt,
	ChkCuryID,
	ChkCuryRGOLAmt,
	ChkDocDate,
	ChkDocType,
	ChkLUpd_DateTime,
	ChkLUpd_Prog,
	ChkLUpd_User,
	ChkPerPost,
	ChkRefNbr,
	ChkSub,
	ChkTerms,
	ComputerName,
	Crtd_DateTime,
	Crtd_Prog,
	Crtd_User,
	DepAcctType,
	DepBankAcct,
	DepBankAcctLen,
	DepBankTransit,
	DepBankTransitLen,
	DepEDIVersion,
	DepEntryClass,
	DepISOCntry,
	DepPNDate,
	DepPNStatus,
	DepPNTaxPmt,
	DepRecord,
	DepUser1,
	DepUser10,
	DepUser2,
	DepUser3,
	DepUser4,
	DepUser5,
	DepUser6,
	DepUser7,
	DepUser8,
	DepUser9,
	EditScrnNbr,
	FilACHCompanyID,
	FilACHCompanyIDLen,
	FilACHCompanyName,
	FilACHCompanyNameLen,
	FilACHImmDest,
	FilACHImmDestLen,
	FilACHImmDestN,
	FilACHImmDestNLen,
	FilACHImmOrig,
	FilACHImmOrigLen,
	FilACHImmOrigN,
	FilACHImmOrigNLen,
	FilCrLf,
	FormatID,
	KeepDelete,
	LUpd_DateTime,
	LUpd_Prog,
	LUpd_User,
	PerAppl,
	RecordSumAmt,
	RecordSummary,
	RecSection,
	RecType,
	SKFuture01,
	SKFuture02,
	SKFuture03,
	SKFuture04,
	SKFuture05,
	SKFuture06,
	SKFuture07,
	SKFuture08,
	SKFuture09,
	SKFuture10,
	SKFuture11,
	SKFuture12,
	User1,
	User10,
	User2,
	User3,
	User4,
	User5,
	User6,
	User7,
	User8,
	User9,
	ValueString,
	VchAmt,
	VchAmtInChkCury,
	VchCpnyID,
	VchCpnyIDEIN,
	VchCuryAmt,
	VchCuryDiscAmt,
	VchCuryID,
	VchCuryMultDiv,
	VchCuryOrigDocAmt,
	VchCuryRate,
	VchDiscAmt,
	VchDocDesc,
	VchDocType,
	VchInvcDate,
	VchInvcNbr,
	VchPONbr,
	VchRefNbr,
	VchUser1,
	VchUser2,
	VchUser3,
	VchUser4,
	VchUser5,
	VchUser6,
	VchUser7,
	VchUser8,
	VendCust,
	VendID,
	VendName
)
select d.AdjCrtd_DateTime,
	d.AdjCrtd_Prog,
	d.AdjCrtd_User,
	d.AdjS4Future01,
	d.AdjS4Future02,
	d.AdjS4Future03,
	d.AdjS4Future04,
	d.AdjS4Future05,
	d.AdjS4Future06,
	d.AdjS4Future07,
	d.AdjS4Future08,
	d.AdjS4Future09,
	d.AdjS4Future10,
	d.AdjS4Future11,
	d.AdjS4Future12,
	d.BnkAcctType,
	d.BnkBankAcct,
	d.BnkBankTransit,
	d.BnkOrigDFI,
	d.BnkPNDate,
	d.BnkPNStatus,
	d.BnkUser1,
	d.BnkUser10,
	d.BnkUser2,
	d.BnkUser3,
	d.BnkUser4,
	d.BnkUser5,
	d.BnkUser6,
	d.BnkUser7,
	d.BnkUser8,
	d.BnkUser9,
	d.ChkAcct,
	d.ChkBatEFTGrp,
	d.ChkBatNbr,
	d.ChkBatSeq,
	d.ChkCpnyID,
	d.ChkCuryAmt,
	d.ChkCuryDiscAmt,
	d.ChkCuryID,
	d.ChkCuryRGOLAmt,
	d.ChkDocDate,
	d.ChkDocType,
	d.ChkLUpd_DateTime,
	d.ChkLUpd_Prog,
	d.ChkLUpd_User,
	d.ChkPerPost,
	d.ChkRefNbr,
	d.ChkSub,
	d.ChkTerms,
	d.ComputerName,
	d.Crtd_DateTime,
	d.Crtd_Prog,
	d.Crtd_User,
	d.DepAcctType,
	d.DepBankAcct,
	d.DepBankAcctLen,
	d.DepBankTransit,
	d.DepBankTransitLen,
	d.DepEDIVersion,
	d.DepEntryClass,
	d.DepISOCntry,
	d.DepPNDate,
	d.DepPNStatus,
	d.DepPNTaxPmt,
	d.DepRecord,
	d.DepUser1,
	d.DepUser10,
	d.DepUser2,
	d.DepUser3,
	d.DepUser4,
	d.DepUser5,
	d.DepUser6,
	d.DepUser7,
	d.DepUser8,
	d.DepUser9,
	d.EditScrnNbr,
	d.FilACHCompanyID,
	d.FilACHCompanyIDLen,
	d.FilACHCompanyName,
	d.FilACHCompanyNameLen,
	d.FilACHImmDest,
	d.FilACHImmDestLen,
	d.FilACHImmDestN,
	d.FilACHImmDestNLen,
	d.FilACHImmOrig,
	d.FilACHImmOrigLen,
	d.FilACHImmOrigN,
	d.FilACHImmOrigNLen,
	d.FilCrLf,
	d.FormatID,
	d.KeepDelete,
	d.LUpd_DateTime,
	d.LUpd_Prog,
	d.LUpd_User,
	d.PerAppl,
	d.RecordSumAmt,
	d.RecordSummary,
	d.RecSection,
	d.RecType,
	d.SKFuture01,
	d.SKFuture02,
	d.SKFuture03,
	d.SKFuture04,
	d.SKFuture05,
	d.SKFuture06,
	d.SKFuture07,
	d.SKFuture08,
	d.SKFuture09,
	d.SKFuture10,
	d.SKFuture11,
	d.SKFuture12,
	d.User1,
	d.User10,
	d.User2,
	d.User3,
	d.User4,
	d.User5,
	d.User6,
	d.User7,
	d.User8,
	d.User9,
	d.ValueString,
	d.VchAmt,
	d.VchAmtInChkCury,
	d.VchCpnyID,
	d.VchCpnyIDEIN,
	d.VchCuryAmt,
	d.VchCuryDiscAmt,
	d.VchCuryID,
	d.VchCuryMultDiv,
	d.VchCuryOrigDocAmt,
	d.VchCuryRate,
	d.VchDiscAmt,
	d.VchDocDesc,
	d.VchDocType,
	d.VchInvcDate,
	d.VchInvcNbr,
	d.VchPONbr,
	d.VchRefNbr,
	d.VchUser1,
	d.VchUser2,
	d.VchUser3,
	d.VchUser4,
	d.VchUser5,
	d.VchUser6,
	d.VchUser7,
	d.VchUser8,
	d.VendCust,
	d.VendID,
	d.VendName
from den_dev_app.dbo.XDDFile_Wrk d
left join shopper_dev_app.dbo.XDDFile_Wrk s
	on d.vendId = s.vendId
where s.vendId is null

---------------------------------------------
-- permissions
---------------------------------------------
grant execute on wrkVendor to BFGROUP
go

grant execute on wrkVendor to MSDSL
go

grant control on wrkVendor to MSDSL
go

grant execute on wrkVendor to MSDynamicsSL
go